version: "3"
services: 
  camisetas:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 33308:3306

  adminer:
    image: adminer:latest
    restart: "no"
    ports:
      - 8181:8080